import React, { useEffect, useState } from 'react';
import { FlatList, StyleSheet, Text, View, Alert, TouchableOpacity } from 'react-native';
import { supabase } from '../lib/supabase';
import jsPDF from 'jspdf';

// FlatList reference:
// React Native Tutorial 10 - FlatList https://www.youtube.com/watch?v=TTvWoTKbZ3Y&list=PLS1QulWo1RIb_tyiPyOghZu_xSiCkB1h4&index=10 by Programming Knowledge
// CRUD Reference

// Cooper Codes "Supabase Database Course - Fetch, Create, Modify, Delete Data (React / Supabase CRUD Tutorial)." YouTube,
// https://www.youtube.com/watch?v=4yVSwHO5QHU
// Uses Read logic from PGA Dashboard

// SupaBase Docs on Javascript https://supabase.com/docs/reference/javascript/select

// React Native Docs Display Image https://reactnative.dev/docs/image

// "Generating PDF Files with jsPDF Library in JavaScript: Quick Start Guide" by Code with Yousef, 
// YouTube Video: https://www.youtube.com/watch?v=i7EOZB3a1Vs

type Lesson = {
  Lessonid: string;
  created_at: string;
  feedback: string;
  drills: string[];
  area: string;
};

export default function ViewLessonsGolfer() {
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchLessons = async () => {
      setLoading(true);
      try {
        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession();

        if (sessionError) throw sessionError;

        const golferId = session?.user.id;

        if (!golferId) {
          throw new Error('User not authenticated');
        }

        const { data: lessonsData, error: lessonsError } = await supabase
          .from('Lesson1')
          .select('Lessonid, created_at, feedback, area, drills:AssignedDrills(drill_id)')
          .eq('GolferID', golferId)
          .order('created_at', { ascending: false });

        if (lessonsError) throw lessonsError;

        const mappedLessons = await Promise.all(
          lessonsData.map(async (lesson: any) => {
            const drillIds = lesson.drills.map((d: any) => d.drill_id);

            const { data: drillNames, error: drillError } = await supabase
              .from('drills')
              .select('name')
              .in('drill_id', drillIds);

            if (drillError) throw drillError;

            return {
              ...lesson,
              drills: drillNames.map((d: any) => d.name),
            };
          })
        );

        setLessons(mappedLessons as Lesson[]);
      } catch (error) {
        Alert.alert('Error', error instanceof Error ? error.message : 'An error occurred');
      } finally {
        setLoading(false);
      }
    };

    fetchLessons();
  }, []);

  // PDF Generation
  const generatePDF = (lesson: Lesson) => {
    const doc = new jsPDF();
  
    // Header Section
    doc.setFillColor(76, 175, 80); // Green Background
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(26); // Larger Title
    doc.setFont('helvetica', 'bold');
    doc.text('Golf IQ Pro - Lesson Report', 105, 20, { align: 'center' });
  
    // Add some vertical spacing
    let yPos = 50;
  
    // Date
    doc.setTextColor(51, 51, 51);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(`Date:`, 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(`${new Date(lesson.created_at).toLocaleDateString()}`, 60, yPos);
    yPos += 20;
  
    // Lesson Area
    doc.setFont('helvetica', 'bold');
    doc.text(`Area of Game:`, 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(lesson.area, 80, yPos);
    yPos += 30;
  
    // Section Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, yPos, 190, yPos);
    yPos += 20;
  
    // Drills Assigned
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Assigned Drills:', 20, yPos);
    yPos += 15;
  
    doc.setFontSize(18);
    doc.setFont('helvetica', 'normal');
    const drillText = lesson.drills.length > 0 ? lesson.drills.join(', ') : 'None';
    doc.text(drillText, 20, yPos, { maxWidth: 170, align: 'left' });
    yPos += 30;
  
    // Feedback
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('Coach Feedback:', 20, yPos);
    yPos += 15;
  
    doc.setFontSize(18);
    doc.setFont('helvetica', 'normal');
    doc.text(lesson.feedback, 20, yPos, { maxWidth: 170, align: 'left' });
  
    yPos += 50;
  
    // Footer
    doc.setFontSize(14);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Golf IQ Pro', 20, 280);
  
    // Save PDF
    doc.save(`Lesson_${lesson.Lessonid}.pdf`);
  };
  

  const renderLesson = ({ item }: { item: Lesson }) => (
    <View style={styles.lessonCard}>
      <Text style={styles.area}>Area: {item.area}</Text>
      <Text style={styles.date}>Date: {new Date(item.created_at).toLocaleDateString()}</Text>
      <Text style={styles.feedback}>Feedback: {item.feedback}</Text>
      <Text style={styles.drills}>
        Drills: {item.drills.length > 0 ? item.drills.join(', ') : 'None'}
      </Text>
      <TouchableOpacity
        style={styles.button}
        onPress={() => generatePDF(item)}
      >
        <Text style={styles.buttonText}>Download PDF</Text>
      </TouchableOpacity>
    </View>
  );

  return (
    <View style={styles.container}>
      {loading ? (
        <Text>Loading lessons...</Text>
      ) : (
        <FlatList
          data={lessons}
          keyExtractor={(item) => item.Lessonid}
          renderItem={renderLesson}
          contentContainerStyle={styles.listContainer}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#f9f9f9',
  },
  listContainer: {
    paddingBottom: 16,
  },
  lessonCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  area: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  date: {
    fontSize: 14,
    color: '#666',
  },
  feedback: {
    fontSize: 16,
    color: '#555',
    marginBottom: 8,
  },
  drills: {
    fontSize: 14,
    color: '#444',
    marginBottom: 8,
  },
  button: {
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});